import Head from "next/head"
import FormBuilder from "@/components/modules/FormBuilder"

export default function Home() {
  return (
    <>
      <Head>
        <title>Dynamic Forms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FormBuilder />
      </main>
    </>
  )
}
